In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [4]:
data = pd.read_csv("mobile_price_classification.csv")

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        1841 non-null   object 
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [6]:
data['n_cores'] = data['n_cores'].fillna(data['n_cores'].mode()[0])
data['n_cores'] = np.where(data['n_cores'] == 'x', '0', data['n_cores'])
data['n_cores']  = data['n_cores'].astype('int')

In [7]:
X, y = data.iloc[:, :-1].values, data.iloc[:, -1].values

In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

### KNN

In [9]:
parameter_knn = {'n_neighbors': [1,2,3,4,5,6,7,8,9,10,11,12, 15,16,20]}

In [10]:
KNN = KNeighborsClassifier()
knn_grid = GridSearchCV(KNN, param_grid=parameter_knn, scoring='accuracy', cv=10)
knn_grid_random = RandomizedSearchCV(KNN, param_distributions=parameter_knn, scoring='accuracy', cv=10)

In [11]:
knn_grid.fit(X, y)
knn_grid.best_params_

{'n_neighbors': 12}

In [12]:
knn_grid.fit(X, y)
knn_grid.best_score_

0.9344999999999999

In [13]:
knn_grid_random.fit(X, y)
knn_grid_random.best_score_

0.9344999999999999

### Naive Baiyes

In [14]:
np.random.seed(10)
a = np.random.dirichlet(np.ones(4),size=20)

In [15]:
List = [i for i in a]

In [16]:
parameter_baiyes = {'priors': List}

In [17]:
Baiyes = GaussianNB()

In [18]:
baiyes_grid =  GridSearchCV(Baiyes, param_grid=parameter_baiyes, scoring='accuracy', cv=10)
baiyes_grid_random = RandomizedSearchCV(Baiyes, param_distributions=parameter_baiyes, scoring='accuracy', cv=10)

In [19]:
baiyes_grid.fit(X,y)

GridSearchCV(cv=10, estimator=GaussianNB(),
             param_grid={'priors': [array([0.38006215, 0.00540181, 0.2586653 , 0.35587074]),
                                    array([0.26597509, 0.09812892, 0.08506272, 0.55083327]),
                                    array([0.04116787, 0.0205525 , 0.25695642, 0.68132322]),
                                    array([0.00118286, 0.21462998, 0.50070639, 0.28348078]),
                                    array([0.23793643, 0.06419401, 0.46467151, 0.23319805]),
                                    array([0.30985002, 0.060...
                                    array([0.32739036, 0.03117513, 0.09220679, 0.54922772]),
                                    array([0.62384426, 0.08655271, 0.24848096, 0.04112207]),
                                    array([0.18574073, 0.47598087, 0.15614164, 0.18213675]),
                                    array([0.04311669, 0.47544344, 0.08925986, 0.39218001]),
                                    array([0.16126386, 0.59696874, 0.01637712, 0.22539028]),
                                    array([0.2034134 , 0.54423153, 0.22866286, 0.02369221]),
                                    array([0.34157554, 0.23217662, 0.33915336, 0.08709448])]},
             scoring='accuracy')

In [20]:
baiyes_grid.best_params_

{'priors': array([0.20576641, 0.20085726, 0.33937841, 0.25399793])}

In [21]:
baiyes_grid.best_score_

0.8029999999999999

In [22]:
baiyes_grid_random.fit(X,y) 

RandomizedSearchCV(cv=10, estimator=GaussianNB(),
                   param_distributions={'priors': [array([0.38006215, 0.00540181, 0.2586653 , 0.35587074]),
                                                   array([0.26597509, 0.09812892, 0.08506272, 0.55083327]),
                                                   array([0.04116787, 0.0205525 , 0.25695642, 0.68132322]),
                                                   array([0.00118286, 0.21462998, 0.50070639, 0.28348078]),
                                                   array([0.23793643, 0.06419401, 0.46467151, 0.23319805]),
                                                   array([0...
                                                   array([0.32739036, 0.03117513, 0.09220679, 0.54922772]),
                                                   array([0.62384426, 0.08655271, 0.24848096, 0.04112207]),
                                                   array([0.18574073, 0.47598087, 0.15614164, 0.18213675]),
                                                   array([0.04311669, 0.47544344, 0.08925986, 0.39218001]),
                                                   array([0.16126386, 0.59696874, 0.01637712, 0.22539028]),
                                                   array([0.2034134 , 0.54423153, 0.22866286, 0.02369221]),
                                                   array([0.34157554, 0.23217662, 0.33915336, 0.08709448])]},
                   scoring='accuracy')

In [23]:
baiyes_grid_random.best_params_

{'priors': array([0.24198012, 0.21157226, 0.37666174, 0.16978587])}

In [24]:
baiyes_grid_random.best_score_

0.7935

### Decision Tree


In [25]:
k = [i for i in range(20)]
k.append('sqrt')
k.append('log2')

In [26]:
parameter_dt = {'max_features': k}

In [27]:
Dt = DecisionTreeClassifier()

In [29]:
dt_grid =  GridSearchCV(Dt, param_grid=parameter_dt, scoring='accuracy', cv=10)
dt_grid_random = RandomizedSearchCV(Dt, param_distributions=parameter_dt, scoring='accuracy', cv=10)

In [31]:
dt_grid.fit(X,y)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(),
             param_grid={'max_features': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                          12, 13, 14, 15, 16, 17, 18, 19,
                                          'sqrt', 'log2']},
             scoring='accuracy')

In [32]:
dt_grid.best_params_

{'max_features': 14}

In [33]:
dt_grid.best_score_

0.8415000000000001

In [40]:
dt_grid_random.fit(X,y)

RandomizedSearchCV(cv=10, estimator=DecisionTreeClassifier(),
                   param_distributions={'max_features': [0, 1, 2, 3, 4, 5, 6, 7,
                                                         8, 9, 10, 11, 12, 13,
                                                         14, 15, 16, 17, 18, 19,
                                                         'sqrt', 'log2']},
                   scoring='accuracy')

In [41]:
dt_grid_random.best_params_

{'max_features': 19}

In [42]:
dt_grid_random.best_score_

0.8310000000000001

### SVM

In [60]:
k = ['linear', 'poly', 'sigmoid']#,'precomputed']
d = [3,4]
g = ['scale','auto']

In [61]:
parameter_svc = {'kernel': k, 'gamma' : g, 'degree': d}

In [62]:
svc = SVC()

In [63]:
svc_grid =  GridSearchCV(svc, param_grid=parameter_svc, scoring='accuracy', cv=10)
svc_grid_random = RandomizedSearchCV(svc, param_distributions=parameter_svc, scoring='accuracy', cv=10)

#### Doubt: How does linear kernel have gamma parameter?

In [64]:
svc_grid.fit(X,y)
svc_grid.best_params_

{'degree': 3, 'gamma': 'scale', 'kernel': 'linear'}

In [65]:
svc_grid.best_score_

0.9715

In [66]:
svc_grid_random.fit(X,y)
svc_grid_random.best_params_

{'kernel': 'linear', 'gamma': 'auto', 'degree': 4}

In [67]:
svc_grid_random.best_score_

0.9715